### ISSUE TITLE
some country highlighting

### ISSUE THREAD

**Issue by pokane84** [mjs2020/trademap#37]
When filtered on “Countries”, “Exports”, “Electric Current” for both London and the East Midlands in 2013, the export legend highlights two partners with zero figures with “not enough data to map” stated underneath.

**Comment by mjs2020** [comment]
The Czech Republic and Poland are the only partners with a record of trade
for electric current in 2013 with London. However the records show both
import and export values of 0. Perhaps we should filter out data records
where import and export is 0? Or is it useful to keep these in order to
differentiate from countries for which we don't have data?

Regarding legend and wording: when a filter selection returns data for less
than 4 partners these are shown in the same colour and the wording "Not
enough data to map" is used in the legend. Thus behaviour and wording can
be changed if you think it is not correct.

**Comment by pokane84** [comment]
Content to close this and keep data as it is.
